### PR TITLE
Newposts

### PR DESCRIPTION
**Pull request by mokaixu**
Added tshirt post and CSters post? (please work)

### CODE REVIEW

**Comment by annalorimer** [comment]
Hey so the commits from your other PR's keep getting included in any new pull requests you make. I'm not entirely sure what you need to do to fix this without actually looking at what you're doing 😛 

Maybe set up a time to meet with either @evykassirer or I to sort this out?

**Comment by fboxwala** [comment]
@mokaixu are you making a new branch off of master _every time_  you work on a new feature?

When you open up a terminal to start working on a new feature always do the following steps before anything else:

`git checkout master`
`git checkout -b newfeaturebranch`

**Comment by fboxwala** [comment]
also please use more descriptive commit messages. ie. "adds file for csters event" instead of "adds file"

**Comment by annalorimer** [comment]
@mokaixu Let us know if you need any help 😃

**Pull request closed without merging**
