### PR TITLE
FAQ, with updates

### PR DESCRIPTION
**Pull request by ehashman**
@ynasser, I made some of the changes I suggested on your PR. Can I get your signoff and maybe someone else's for a merge of this? :)

### CODE REVIEW

**Comment by void-elf** [comment]
:sheep: 
lgtm :)

**Comment by evykassirer** [comment]
I addd a comment but I think it was in the wrong place again, sorry

**Comment by ehashman** [comment]
Thanks for the +1 @ynasser, I will merge :tada:

**Comment by ehashman** [comment]
(note this will automatically mark your pull request as merged)

**Pull request merged**
