### PR TITLE
Policies

### PR DESCRIPTION
**Pull request by claricen**
Adds policies in nav; puts code of conduct under it

### CODE REVIEW

**Comment by fboxwala** [comment]
can you submit a PR without the "update fork" commit? You can revert back to before that commit and update your fork from the command line with `git rebase upstream/master`, instead of making a PR in your repo for it.

**Comment by claricen** [comment]
which commit was that, 1d2a0d1?

**Comment by fboxwala** [comment]
removing that one would also be good, but I was referring to `4db340a`

**Comment by ehashman** [comment]
Yeah this isn't in a mergeable state. Clare, here's what I want you to try:

```
git checkout master         # Go back to your master 
git reset --hard HEAD^      # Remove the one extraneous commit from your master
git fetch upstream          # Get new commits from current master
git rebase upstream/master  # Rebase your master to match the upstream
git checkout -b policies2   # Make a new branch for your PR
git cherry-pick c5dfa0b     # Grab only the commit you want for it
git push origin HEAD        # Push the new branch to GitHub
```

And then make a pull request from the policies2 branch, and we'll talk about cleaning up your commit tree once you're successful :) If you get stuck, please hop on #wics-sys.

**Comment by claricen** [comment]
thanks! Fatema walked me through it.

**Pull request closed without merging**
