### PR TITLE
Police Policy/lines changed

### PR DESCRIPTION
**Pull request by SZain**
Kindly check it,  if it worked.

### CODE REVIEW

**Comment by ehashman** [comment]
Hi @SZain! It looks like your change didn't work :( When Markdown is compiled, all extra blank lines are removed; they don't affect the final spacing.

To fix this bug, we need to update the CSS stylesheets as I indicated in the issue. Would you like me to walk you through that?

**Comment by SZain** [comment]
I apologise as i am novice user, it would be great if you point it out.
Thanks

**Comment by SZain** [comment]
I added few changes if it worked.

**Comment by ehashman** [comment]
Hi @SZain: editing the markdown will not change anything, as our renderer will still output the same thing! We need to change the CSS styles, as per #115. I'm going to close this PR, as unfortunately it does not fix the issue in question, which you could see on the review app.

**Pull request closed without merging**
