### PR TITLE
Add a mention of the library to the Office section

### PR DESCRIPTION
**Pull request by zarinaaa**
This addresses part of Issue #193.

### CODE REVIEW

**Comment by ehashman** [comment]
We have a copy of cracking the coding interview? This is news to me.

Even if we do, I'd prefer we advertise our materials more generally, such as "independent tech feminist publications (such as the Recompiler and Model View Culture) and a collection of technical books". Then if we like we could make a separate, hidden page for the library with a full list.

**Comment by arshiamufti** [comment]
Yeah we've had one. I think it was @evykassirer's old copy. I like the general description as well.

**Comment by evykassirer** [comment]
If we specially mention mvc's title I don't see why we can't mention ctci (I've already had a few people ask me if there's a copy in the office)

**Comment by ehashman** [comment]
I only used the names in the general description because "independent tech feminist publications" is the sort of phrase for which actual examples are illustrative. Doesn't a full library listing on another page satisfy your requirement?

I think it is misleading to use the original wording of this PR because it implies our library is limited to zines and interview prep material, which is inaccurate.

**Comment by evykassirer** [comment]
(we're working on not having the video commit lumped in with this PR)

**Comment by ehashman** [comment]
```
git rebase master
```

on the books branch should fix it.

Edit: You will need to force push this commit after that.

**Comment by evykassirer** [comment]
yup that's what we did, I think it's fixed

**Comment by ehashman** [comment]
Deployed.

**Pull request merged**
