### PR TITLE
Update the IRC doc to link to #wics-sys

### PR DESCRIPTION
**Pull request by ehashman**

### CODE REVIEW

**Comment by fboxwala** [comment]
Taurine has a limited number of OFTC connections right? Should we be directing people to get on sucrose or corn syrup instead?

**Comment by ehashman** [comment]
If we hit the connection limit, then someone from syscom should ping the OFTC admins and ask them to raise it.

**Comment by meltedesco** [comment]
Have done that, multiple times. No response from OFTC, and seems there is
no difference in the connection limit. :/ Don't know how to get through to
them.

melted

**Comment by ehashman** [comment]
In that case, I've noticed the ident server doesn't seem to be affecting OFTC connections. We should probably update/bounce it to ensure that's the case. But again, whine at csc-syscom :P

**Pull request merged**
