### PR TITLE
Changes irc guide link

### PR DESCRIPTION
**Pull request by nivasini**

### CODE REVIEW

**Comment by ehashman** [comment]
The linked wiki requires a Quest account to access. Do we want to create a new, public repo on the GitLab instead? e.g. wics/public

**Comment by fboxwala** [comment]
Do we have other things we would want to make public besides this? 

We could also just copy these instructions to a hidden page on the website instead

**Comment by ehashman** [comment]
I like the idea of having a public wiki on the GitLab; we can migrate some pages there (and leave behind a link), in a similar way that I've migrated at least one page from wics/for-wics-eyes-only to wics/documentation.

**Comment by ehashman** [comment]
(created the repo, btw: https://git.uwaterloo.ca/wics/public/wikis/home)

**Comment by ehashman** [comment]
Closing this PR, as the feedback hasn't been addressed and the new link is not accessible to non-WiCS members, which doesn't make sense for our public website.

**Pull request closed without merging**
