### PR TITLE
took text recommendation changes

### PR DESCRIPTION
**Pull request by mokaixu**
accounted for edits by team

### CODE REVIEW

**Comment by evykassirer** [comment]
why isn't this in #300 ? did you make a new branch?

**Comment by mokaixu** [comment]
Oh I added an extra volunteer in the branch name my bad :(
Do you want me to redo this and move it to 300?

**Comment by evykassirer** [comment]
if you still have the old branch, you should make the change there yeah

**Comment by fat1996** [comment]
Can this PR be closed? Seems like all the changes are in #300.

**Review by fat1996 — CHANGES_REQUESTED** [review]
@mokaixu Can this PR be closed? Seems like all the changes are in #300.

**Pull request closed without merging**
