### PR TITLE
fixes broken filename for wics-csc event

### PR DESCRIPTION
**Pull request by fboxwala**

### CODE REVIEW

**Comment by evykassirer** [comment]
```
WARNING: There are 2 variants of "updated-wics-csc-s16" with lang en
WARNING:    /tmp/build_d7856f17c591c8b142fe244b16d417ca/wics-uw-website-f440a2e/content/S2016/S16-event-updated-wics-csc.md
WARNING:    /tmp/build_d7856f17c591c8b142fe244b16d417ca/wics-uw-website-f440a2e/content/S2016/S16-updated-event-wics-csc.md
CRITICAL: RuntimeError: File /tmp/build_d7856f17c591c8b142fe244b16d417ca/wics-uw-website-f440a2e/public/2016/07/updated-wics-csc-s16/index.html is to be overwritten
 !     Push rejected, failed to compile Pelican app
```

**Comment by evykassirer** [comment]
did you not delete the old file?

**Comment by fboxwala** [comment]
git rm is real hard for me apparently.

**Comment by evykassirer** [comment]
`WARNING: Unable to find /content/S2016/S16-event-updated-wics-csc.md, skipping url replacement.` 😕  same problem?

**Comment by evykassirer** [comment]
_crossed fingers_

**Pull request merged**
