### PR TITLE
Square event details added

### PR DESCRIPTION
**Pull request by bdamerac**
A

### CODE REVIEW

**Comment by evykassirer** [comment]
See how this one also has all the commits from the tea party? You need to have your master branch identical to the wics version of the website (without any of our new changes) and then a new branch off of that. If you're confused what I mean, feel free to ping me on irc. You can probably close this PR too.

**Comment by bdamerac** [comment]
So do I fork a new repository? I tried doing that and it takes me to the old one!

**Comment by evykassirer** [comment]
Depends - if you were working in master branch, one way to reset is deleting your fork (delete the repository) and making a new one. There are easier ways to do it though - try `git reset --hard origin/master`

**Comment by ehashman** [comment]
`git reset --hard origin/master` won't fix anything because @Bhargavi1997 has pushed those changes out to master. @Bhargavi1997, did you set up an `upstream` remote per the README? Because in that case, you can `git fetch upstream && git reset --hard upstream/master` while you have your master branch checked out.

**Pull request closed without merging**
