### PR TITLE
Update W15-event-research-showcase.md

### PR DESCRIPTION
**Pull request by fboxwala**

### CODE REVIEW

**Comment by SrishtiG** [comment]
Looks good. Still need to update speakers

**Comment by ehashman** [comment]
Lolwat, why was this merged? Diff says you added a space to change "MC" to "M C" ~.~

**Comment by SrishtiG** [comment]
I corrected that after merging, and my correction was merged too … the website needs to be deployed. 

-Srishti 

From: Elana Hashman
Sent: ‎Thursday‎, ‎February‎ ‎5‎, ‎2015 ‎1‎:‎11‎ ‎PM
To: wics-uw/website
Cc: Srishti Gupta

Lolwat, why was this merged? Diff says you added a space to change "MC" to "M C" ~.~

**Comment by ehashman** [comment]
Yes, I saw that in the PR that came after this one, but this should not have been merged.

**Pull request merged**
