### PR TITLE
[WIP] Add Machine Usage Agreement hidden page

### PR DESCRIPTION
**Pull request by ehashman**
First draft. We should adopt this in a committee meeting! I haven't done the summary yet.

### CODE REVIEW

**Comment by ehashman** [comment]
There are a bunch of typos in here; I started working on them on a local copy somewhere but apparently never pushed to my remote.

**Comment by evykassirer** [comment]
@ehashman Should we continue to work on this in the coming term? Did you want to edit, or should we take over?

**Comment by ehashman** [comment]
@evykassirer: there's a local copy of many more edits done on one of the office terminals. I _should_ be able to finish this, but in the entirely possible case I don't, at the very least I should bring this up to date with that.

**Comment by fboxwala** [comment]
Did you update with the office terminal version?

**Comment by ehashman** [comment]
Yes I did, on Sep. 28 (but they are dated Feb. 20). I am going to merge this into its own branch on master.

**Comment by ehashman** [comment]
See https://github.com/wics-uw/website/tree/mua for the upstream branch. Going to close this PR.

**Pull request closed without merging**
