### PR TITLE
Code of conduct updates

### PR DESCRIPTION
**Pull request by ehashman**
We will need to ratify these changes as a committee.

### CODE REVIEW

**Comment by meltedesco** [comment]
++, I am fine with these changes to the code of conduct

**Comment by annalorimer** [comment]
++

**Comment by SrishtiG** [comment]
+++

**Comment by evykassirer** [comment]
++

**Comment by ehashman** [comment]
@julianguyen @jennyzsun @rosexu @fboxwala @ChristinaLiu and Helen need to sign off on this as well!

**Comment by fboxwala** [comment]
++

**Comment by ChristinaLiu** [comment]
++

**Comment by jennyzsun** [comment]
++

**Comment by rosexu** [comment]
++

**Comment by julianguyen** [comment]
++

**Pull request merged**
