### PR TITLE
Removed the calendar and made the volunteer page visible 

### PR DESCRIPTION
**Pull request by fat1996**

### CODE REVIEW

**Comment by arshiamufti** [comment]
- why are there two pull requests? Leave this one open and close the second #263 since this one seems to have both your changes. You might also want to update the title of this pull request.
- squash your two commits into one (documentation for doing this is in the README or just post in wics-sys if you're having trouble)

Also, in general it's a good idea to give your branches better names than `task` but this is fine for now.

**Comment by fboxwala** [comment]
@arshiamufti Actually I would say its pretty okay for this to be two commits, since @fat1996 is changing two files. Generally I like the rule to be "one file changed == one commit".

**Comment by arshiamufti** [comment]
Sounds good to me--go ahead and merge.

**Comment by evykassirer** [comment]
@fboxwala is it possible to change it so it doesn't say ehashman deployed?

**Comment by evykassirer** [comment]
@fat1996 you can see at https://wics-site-pr-264.herokuapp.com/ that the navbar still overflows (tags is on the next line) - you'll have to make the volunteer tab title shorter

**Comment by annalorimer** [comment]
"Volunteer" as the tab name should be fine

**Comment by fat1996** [comment]
I've changed the tab name to just 'volunteer'.

**Comment by evykassirer** [comment]
love it 😍

**Pull request merged**
