### PR TITLE
Created exec-S16 committee pages; fixes #166

### LINKED ISSUE #166: Update committee members for S16
See #59 for what that might look like, in terms of updating links, archiving a copy of the previous committee page, etc.

### PR DESCRIPTION
**Pull request by techiechelle**

### CODE REVIEW

**Comment by ehashman** [comment]
Hi Michelle!

This pull request appears to be garbled. You can take a look at the rendered markdown page here: https://github.com/techiechelle/website/blob/nmaliauw/content/pages/exec-S16.md

Do you have someone to assist you with this pull request?

**Comment by evykassirer** [comment]
I can work with you tomorrow after the meeting @techiechelle :) I think you'll have to change a couple other files too

**Comment by evykassirer** [comment]
really nice job getting this much done on your own though 🎉 I'm glad you were able to get stuff done despite not being able to come to the ramp up session 😄

**Comment by techiechelle** [comment]
@ehashman eek. Thanks for catching that. I made an update. Would you prefer if I delete this branch and made a new pull request.

@evykassirer , I was going to ask you about the other files, like exec.md and past-execs.md

**Comment by evykassirer** [comment]
If you can make the changes in your branch, it'll update here automatically and that would work fine.
If closing this pull request and making a new one feels better for you, that's also fine
I noticed you already got the list looking good, so sticking to this PR seems like the better choice.

Yeah! Check out the other files and see what the changes are and try to figure out why they were changed (playing around on the website to see where those pages exist might help). You'll need to make similar changes for this pull request too.

**Comment by ehashman** [comment]
@techiechelle, I agree that it would make sense to make a new/branch PR. Let's close this one. Let me know if you aren't able to find someone to help you out with this and I'll see if we can schedule some time.

**Pull request closed without merging**
