### PR TITLE
Update constitution values

### PR DESCRIPTION
**Pull request by ehashman**
Addresses #133, building on #134.

### CODE REVIEW

**Comment by ehashman** [comment]
I submitted this and #134 separately to add to readability (in case there are any requested changes just on the formatting commit), but if #134 looks okay, please close that and just merge this one. Thanks!

**Comment by fboxwala** [comment]
Is there a reason we can't have both technical excellence and consensus-building as values?

Also, I kind of want to hold off on merging this until after our due date for new applicants because one of the questions refers to our values and what/if anything they would add or change, and giving them a less-polished version of the values lets them have more to comment on.

**Comment by ehashman** [comment]
> Is there a reason we can't have both technical excellence and consensus-building as values?

I think you misread the commit diff, I just pushed technical excellence to number 7 and inserted consensus-building beforehand.

The only changes are adding consensus-building (a value that has been explicit and should have been explicit), and renaming honesty -> accountability and expanding on that.

**Comment by fboxwala** [comment]
Woops yeah I misread. Okay then LGTM. I'm going to not merge until after next Monday though.

**Comment by ehashman** [comment]
Has the call for applicants gone out? I have been meaning to update this for a while and I'd rather not ask for feedback on our values if we are planning to immediately change them afterwards; that sounds misleading at best, and not compatible with the transparency I'd like to promote. I'd definitely like @wics-uw/contributors to sign off on these changes though. "Honesty" was very rough around the edges and we had missed "consensus-building" and I think this reflects our intent much better now.

**Comment by fboxwala** [comment]
I haven't received the call for volunteers yet. But it's going out today. I can merge it before then, but I don't think we're going to get many more +1's by then. And changing it while the app is out is probably worse?

**Comment by evykassirer** [comment]
I sent it this morning as mentioned yesterday

**Comment by saadiyadesai** [comment]
looks good ++

**Pull request merged**
