### PR TITLE
changed link

### PR DESCRIPTION
**Pull request by mokaixu**

### CODE REVIEW

**Comment by annalorimer** [comment]
Looks like you forgot to make a branch before making changes. You'll have to do that and copy your changes over before we can merge anything :) 

https://github.com/wics-uw/website#contributing-content-to-the-website see

**Comment by evykassirer** [comment]
and if you need help let us know :)

**Comment by evykassirer** [comment]
otherwise looks good!

just another thought - let's add wics-sys mailing list too

https://lists.uwaterloo.ca/mailman/listinfo/wics-sys

**Comment by evykassirer** [comment]
continued in #286

**Pull request closed without merging**
