### PR TITLE
Spring 2017 events and exec page

### PR DESCRIPTION
**Pull request by saadiyadesai**
- Updated the exec page for the spring 2017 committee
- Added all the spring 2017 events

### CODE REVIEW

**Comment by evykassirer** [comment]
here's what it looks like! https://wics-site-pr-330.herokuapp.com/

**Comment by evykassirer** [comment]
seems like the nav bar broke :/ not sure why

**Comment by evykassirer** [comment]
it might be just heroku being bad for the demo app? otherwise everythin glooks good to me!

**Comment by fboxwala** [comment]
The navbar thing I am 90% sure is a heroku deploy issue. I've seen that happen before as well.

**Pull request merged**
